### PR TITLE
Update SCP:SL - Exiled repository link

### PR DESCRIPTION
**Pull request by DzigiBauk**
# Description

Due to some internal issues, the development team switched repositories, making the one that the current egg downloads deprecated. I just changed which repository it's being downloaded from ( Exiled-Team/EXILED -> ExMod-Team/EXILED )

I only changed the link

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
* [X] If some script is needed then it is part of a current yolk or a PR to add one
* [-] The egg was exported from the panel

### CODE REVIEW

**Review by gOOvER — CHANGES_REQUESTED** [review]
please export the egg from the panel

**Comment by gOOvER** [comment]
and btw:
duplicate: #72

you was the second, so your PR will be closed

**Comment by QuintenQVD0** [comment]
Duplicate #72

**Comment by ArdaKaramanx** [comment]
[egg-s-c-p--s-l.json](https://github.com/user-attachments/files/26226017/egg-s-c-p--s-l.json)
[scpslexiledegg-s-c-p--s-l--exiled.json](https://github.com/user-attachments/files/26226019/scpslexiledegg-s-c-p--s-l--exiled.json)

Update Exmod-EXILED and add image

https://github.com/ExMod-Team/EXILED

**Pull request closed without merging**
