### PR TITLE
add: Midnight Ghost Hunt

### LINKED ISSUE #15: [Egg Request]: Midnight Ghost Hunt
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/915810/Midnight_Ghost_Hunt/

### Links for the download

https://store.steampowered.com/app/915810/Midnight_Ghost_Hunt/

### Links for the install docs

https://steamdb.info/app/1118810/subs/

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

- add: Midnight Ghost Hunt
- closes #15 

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [ ] Does your submission pass tests (server is connectable)? (@Toaaa please test)
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Review by Toaaa — CHANGES_REQUESTED** [review]
Server works. But it seems like that the `Game Name` option isn't really changing the name of the server in-game.

**Comment by QuintenQVD0** [comment]
> Server works. But it seems like that the `Game Name` option isn't really changing the name of the server in-game.  

That may be a bug in the server software as ir gets correctly passed to the binary.

**Comment by Toaaa** [comment]
> > Server works. But it seems like that the `Game Name` option isn't really changing the name of the server in-game.
> 
> That may be a bug in the server software as ir gets correctly passed to the binary.

So is this a problem that the MGH devs need to fix?

**Comment by QuintenQVD0** [comment]
> > > Server works. But it seems like that the `Game Name` option isn't really changing the name of the server in-game.
> > 
> > 
> > That may be a bug in the server software as ir gets correctly passed to the binary.
> 
> So is this a problem that the MGH devs need to fix?

I followed their docs on how to change it and you will see it change on the startup tab so there docs are wrong or it is not implemented right

**Review by Toaaa — APPROVED** [review]
👍

**Review by parkervcp — APPROVED** [review]

**Comment by Toaaa** [comment]
> > > > Server works. But it seems like that the `Game Name` option isn't really changing the name of the server in-game.
> > > 
> > > 
> > > That may be a bug in the server software as ir gets correctly passed to the binary.
> > 
> > 
> > So is this a problem that the MGH devs need to fix?
> 
> I followed their docs on how to change it and you will see it change on the startup tab so there docs are wrong or it is not implemented right

It looks like the error is in the startup command. There is just a space missing between the `-Map` and `-Gamename` parameters. Adding a space there fixes the problem.

o1he8
t72ho

**Pull request merged**
