### PR TITLE
ARK:SA fixed a missing space in startup

### PR DESCRIPTION
**Pull request by gOOvER**
# Description

- fixed a missing space in startup cmd
- added dowload url to pelican egg
- exported both eggs again to fix problems

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@gOOvER YOu overwrote the uuid, please revert that

**Comment by gOOvER** [comment]
> @gOOvER YOu overwrote the uuid, please revert that

i only inported the pteroegg and exported it in pelican. Then there is a problem in pelican

**Comment by gOOvER** [comment]
and it looks like, thatr all eggs are masscoverted and never exported from a panel. There are so much errors in these eggs

**Comment by QuintenQVD0** [comment]
> > @gOOvER YOu overwrote the uuid, please revert that
> 
> i only inported the pteroegg and exported it in pelican. Then there is a problem in pelican

yes ofc that is expected, as you must imported the pelican one to keep the same uuid as if an egg is imported withoud one the panel will generate a unique one

**Comment by gOOvER** [comment]
> > > @gOOvER YOu overwrote the uuid, please revert that
> > 
> > 
> > i only inported the pteroegg and exported it in pelican. Then there is a problem in pelican
> 
> yes ofc that is expected, as you must imported the pelican one to keep the same uuid as if an egg is imported withoud one the panel will generate a unique one

alllready fixed

**Comment by QuintenQVD0** [comment]
> and it looks like, thatr all eggs are masscoverted and never exported from a panel. There are so much errors in these eggs. See ptero egg installscript

Most of them still import and work fine, but indeed there are exeptions

**Comment by QuintenQVD0** [comment]
But yet that export is still in my todo list

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thanks

**Pull request merged**
