### PR TITLE
[Satisfactory] 1.0 Release Update

### LINKED ISSUE #73: [Egg Request]: Satisfactory v1.0 Release 9/10
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.satisfactorygame.com/

### Links for the download

https://steamdb.info/app/1690800/

### Links for the install docs

https://satisfactory.wiki.gg/wiki/Dedicated_servers/Configuration_files

### PR DESCRIPTION
**Pull request by lilkingjr1**
# Description

### Egg:
- Removed unused `?listen` flag from startup command.
- Changed Configuration Files to now use the updated INI parser and removed the depreciated `bImplicitSend` setting (it was moved to `mIntValues`).
- Updated the Installation Script and removed the need to delete/create INI config files (thanks to the INI parser).
- Removed the "Upload Crash Reports" Startup Variable because it is now handled in-game via the Server Manager UI.
- Updated description of "[Experimental] Max Players" Startup Variable.
- Updated "[Advanced] Satisfactory Dedicated Server App ID" Startup Variable to be locked to the correct value.

### README:
- Updated top banner with relevant v1.0 information.
- Updated Egg Capabilities list.
- Updated Server Ports information.
- Updated Installation/System Requirements (minimum RAM and Network usage has changed).
- Added warning about Tier 0 to Server Initialization.
- Updated/reorganized Save Files section.
- Added `Exiting abnormally (error code: 130)` warning to Known Errors/Warnings section.

Resolves #73 

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

* [x] You verify that the start command applied does not use a shell script
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by MinerPL** [comment]
After some testing I saw that we can remove 3 parameters from startup command - ServerQueryPort, BeaconPort and multihome.
Now game use only one port (default 7777 tcp/udp)

**Comment by julian-piehl** [comment]
The server crashes when trying to load or create a save game.
No idea if it's a satisfactory, egg, or me problem.

https://pastebin.com/zyr7wwzE

**Comment by lilkingjr1** [comment]
PR should be good to go for review now. Description has been updated. Please use the description change log as the change log for the squash merge, because the commits do not have comments (I was rushing to push them).

For those wanting to test the Egg, please use the updated Egg in this PR and read the extensively updated README.md included with this PR as well.

**Comment by DylanDelobel** [comment]
Used the new egg as a fresh install
No error, no crash for the past 4 hours 🔥

**Comment by lilkingjr1** [comment]
@julian-piehl How much RAM and storage do you have allocated?

**Comment by julian-piehl** [comment]
> @julian-piehl How much RAM and storage do you have allocated?

@lilkingjr1 It currrntly has 6GB RAM and 70 GB Storage available (havent't set storage limit).

**Comment by RobertRR11** [comment]
Have been running a server with this egg for 24 hours without any issues, thx for the quick update

**Comment by QuintenQVD0** [comment]
some changes were made like 5 min ago that may fix your server:
https://store.steampowered.com/news/app/526870/view/4615715344788357373?l=english

**Comment by lilkingjr1** [comment]
Some people were reporting crashing during saving (before the patch today), but I’m not sure if this is an Egg issue… I haven’t experienced this issue at all. I have a feeling there are some edge cases on the Satisfactory side regarding loading/saving 0.8 saves potentially?

**Comment by MonkWho** [comment]
If you are running Wings as a VM on Proxmox, you might experience crashes during world creation. Setting the CPU type to "host" fixes the issue for some people. Not an issue with this egg or update, but hopefully this note might help some other people in the future.

**Comment by lilkingjr1** [comment]
> If you are running Wings as a VM on Proxmox, you might experience crashes during world creation. Setting the CPU type to "host" fixes the issue for some people. Not an issue with this egg or update, but hopefully this note might help some other people in the future.

Good to know! I'll add this to the README later today.

**Comment by julian-piehl** [comment]
> If you are running Wings as a VM on Proxmox, you might experience crashes during world creation. Setting the CPU type to "host" fixes the issue for some people. Not an issue with this egg or update, but hopefully this note might help some other people in the future.

That fixed my problem. Thanks :D

**Comment by gOOvER** [comment]
@lilkingjr1 fyi -multihome works again since the patch

**Comment by lilkingjr1** [comment]
@gOOvER Is `-multihome` explicitly required now though? I thought their latest update made all services of the server listen on all available interfaces by default.

**Comment by lilkingjr1** [comment]
@MonkWho Do you mind sending a screenshot of this "host" CPU setting in Proxmox? I host Wings in a similar fashion, but I'm still a novice at Proxmox and I don't see any option for setting CPU type to "host". Is this setting only available if you are using HA?

**Comment by MonkWho** [comment]
> @MonkWho Do you mind sending a screenshot of this "host" CPU setting in Proxmox? I host Wings in a similar fashion, but I'm still a novice at Proxmox and I don't see any option for setting CPU type to "host". Is this setting only available if you are using HA?

CPU Type Settings are in Hardware section of a VM.

VM > Hardware > Processors > Type

**Comment by lilkingjr1** [comment]
> CPU Type Settings are in Hardware section of a VM.

Huh, interesting... I guess I've just always used `x86-64-v2-AES` and never scrolled all the way down to see the `host` option. I guess `x86-64-v2-AES` is very close (if not the same) to what my host's CPU actually is, so that might be why I don't have any issues with Satisfactory. But I can see now that if people have different host CPUs, or if they choose a Type that limits what CPU opcodes can be called, it could cause an issue if Satisfactory uses, say, MMX, AVX or AES instructions for saving.

I'm debating if this is really an "Egg issue", but I guess a quick note in the README wouldn't hurt either.

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Thank you for catching the Pelican errors!

not a problem, happy I could help

**Comment by lilkingjr1** [comment]
While I could be wrong, it appears Coffee Stain has resolved the issues regarding incorrect interface listening, so I am going to leave out `-multihome` and/or the `-ini` tweak for now. If we need to add them later we can. Additionally, just as a note, I tried adding the `-ini` tweak directly to the Engine.ini file via Configuration Files, but the engine just deletes it on boot leading me to believe it's ignored now as well.

**Pull request merged**
